const productGenre = {
  webSite: "webサイト",
  webApp: "Webアプリ",
  all: "総合",
  material: "資料",
};

export const productList = [
  {
    name: "Jambubble発表資料",
    path: "/materials/Jambubble",
    genre: productGenre.webSite,
    catchcopy: "私たちで作る、私たちだけの音楽体験",
    text: "卒業制作発表資料",
    img: "https://jambubble.dawn-waiting.com/_astro/jamlogo.D3bBYERJ.png",
  },
  {
    name: "Jambubble",
    path: "https://jambubble.dawn-waiting.com",
    genre: productGenre.webSite,
    catchcopy: "私たちで作る、私たちだけの音楽体験",
    text: "一つのプレイリストを、複数人で動的に作り、それぞれが音楽をリクエストできるモバイルアプリ。",
    img: "https://jambubble.dawn-waiting.com/_astro/jamlogo.D3bBYERJ.png",
  },
  {
    name: "Rumos発表資料",
    path: "/materials/Rumos",
    genre: productGenre.material,
    catchcopy: "変わらぬ日々に魔法をかけて。",
    text: "ゼミの発表資料です。",
    img: "https://rumos.dawn-waiting.com/_astro/IMG_7398.BYiirGM4.png",
  },
  {
    name: "DuckShift",
    path: "https://www.duskshift.dawn-waiting.com/",
    genre: productGenre.webApp,
    catchcopy: "見守って、整えて、届けるシフト",
    text: "夜の時間を見守るフクロウのように、無理なく、優しく。働く人のリズムに寄り添うシフト管理アプリ",
    img: "https://www.duskshift.dawn-waiting.com/_astro/duskowl.B8Aq8Uhy.png",
  },
  {
    name: "Rumos",
    path: "https://rumos.dawn-waiting.com/",
    genre: productGenre.all,
    catchcopy: "変わらぬ日々に魔法をかけて。",
    text: "DawnRumosはもう使わなくなった雑貨から、いつもそばにある日用品、さらには家具に至るまであらゆるモノをライトインテリアとして再生し、それらをスマートかつ美しくコントロール。部屋に散らばる光のデバイスを一括で操り、空間全体の世界観そのものを切り替える“雰囲気演出プラットフォーム”です。",
    img: "https://rumos.dawn-waiting.com/_astro/sangria_icon.XcODPnkS.png",
  },
  {
    name: "日々写真館",
    path: "https://hibi.dawn-waiting.com/",
    genre: productGenre.webSite,
    catchcopy: "気ままに切り取る今日の景色",
    text: "お写真ポートフォリオ",
    img: "https://hibi.dawn-waiting.com/_astro/IMG_0168.B7oJDhxL.jpg",
  },
  {
    name: "Dawn",
    path: "https://dawn-waiting.com/",
    genre: productGenre.webSite,
    catchcopy: "継続を凌駕する実行力",
    text: "一つ目のポートフォリオ",
    img: "https://dawn-waiting.com/static/media/dawn_cat.95f7a64e177a4125d31c.png",
  },
];
